### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by prybalko** [paritytech/banana_split#64]
I propose to enable Dependabot for this project
So it automatically updates dependencies with known security issues

For more info:
https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates

**Comment by kirushik** [comment]
Feel free to enable it — but please keep in mind that for Dependabot to actually be useful we'd need to have some more clear-cut flow for _releasing_ new versions of BananaSplit to the users. Just bumping versions in our repo won't be enough.

CC'ing @s3krit here to figure out the release flow. Please pay attention to the #33 issue, it might require some additional steps in the release pipeline (like, pinning the new version to IPFS).
Ideally, the next release would already get this feature, and be hosted through a IPFS gateway instead of some static hosting under our control.

**Comment by prybalko** [comment]
@kirushik I don't have access to the repo's settings. I think I need to be a "collaborator" to do that.

**Comment by prybalko** [comment]
It seems like `Dependabot` is already enabled. Closing this ticket
